# Generated by Django 5.1.6 on 2025-02-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_img', models.ImageField(upload_to='static/images/')),
                ('second_img', models.ImageField(upload_to='static/images/')),
                ('Title', models.CharField(max_length=20)),
                ('Overview_desc', models.CharField(max_length=20)),
                ('adult_price', models.CharField(max_length=20)),
                ('children_price', models.CharField(max_length=20)),
                ('infants_price', models.CharField(max_length=20)),
            ],
        ),
    ]
