# Generated by Django 5.1.6 on 2025-02-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='Things_to_do_desc',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='destination',
            name='Travel_Guide_desc',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AlterField(
            model_name='destination',
            name='Overview_desc',
            field=models.CharField(max_length=1000),
        ),
    ]
